test

diff --git a/.github/workflows/helm.yml b/.github/workflows/helm.yml
--- a/.github/workflows/helm.yml
+++ b/.github/workflows/helm.yml
@@ -1,4 +1,4 @@
-name: Manual k8s (Helm) deployment
+name: k8s (Helm) deployment
 
 on:
   workflow_call:
@@ -22,6 +22,14 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Debug secret access
+        run: |
+          echo "${{ secrets.KUBECONFIG }}" || echo "Failed to access KUBECONFIG secret."
+
+      - name: Debug kubeconfig decoding
+        run: |
+          echo "${{ secrets.KUBECONFIG }}" | base64 --decode || echo "Failed to decode KUBECONFIG secret."
 
       - name: Set up kubeconfig
         run: |
